### ISSUE TITLE
Installation on Pre-Built Developer VM

### ISSUE THREAD

**Issue by iczcrash** [lschilde/Sharing_APEX_SERT_24_1#1]
I've tried to install APEX-SERT with the current pre-built VM.
Is there a workaround?
Also tried to access the App, but without success.

```
=============================================================================
== R E C O M P I L E   C O R E	 S C H E M A
=============================================================================
=============================================================================
== A P P L I C A T I O N   I N S T A L L A T I O N   R E S U L T S
=============================================================================


    APP_ID WORKSPACE		APPLICATION_NAME
---------- -------------------- ------------------------------
       101 SERT 		APEX-SERT
       102 SERT 		APEX-SERT Administration
=============================================================================
== P O S T   I N S T A L L A T I O N   S T E P S
=============================================================================

In order to be able to launch APEX-SERT, paste the following into the System Message
region in the INTERNAL workspace:

<a href="javascript:var launchSERT=window.open('sert/launch/' + $v('pInstance'));"><span class="a-Icon icon-run-page"></span>&nbsp;Launch APEX-SERT</a>

To access the APEX-SERT Admin application, enter the following URL while
substituting HOST, PORT and DAD with those from your APEX environment:

http(s)://HOST:PORT/DAD/f?p=SERT_ADMIN

Please see the APEX-SERT Installation Guide for detailed post-installation steps.

connect as SV_SERT_LAUNCHER for SERT Launcher Web Service part 2
ERROR:
ORA-12514: Cannot connect to database. Service orcl is not registered with the
listener at host 127.0.0.1 port 1521. (CONNECTION_ID=JWBoWPsFHS7gYwEAAH/HNQ==)
Help: https://docs.oracle.com/error-help/db/ora-12514/


[oracle@localhost sert_240100]$ 
```

I can also see a error for the PDF package in the logfile.

```
620/7    PL/SQL: Statement ignored                                              
620/7    PLS-00905: object SV_SERT_240100.PL_FPDF is invalid 
```

Full logfile attached.
[SERT_install_2024-10-26_11-19-29.log](https://github.com/user-attachments/files/17530527/SERT_install_2024-10-26_11-19-29.log)

**Comment by lschilde** [comment]
Please try it on VM that is not 21c or 23ai. Otherwise pdf packages do not
get compiled, I am aware of it but have to find time to go over it before
it will work in these person of DBs.

On Saturday, October 26, 2024, iczcrash ***@***.***> wrote:
> I've tried to install APEX-SERT with the current pre-built VM.
> Is there a workaround?
> Also tried to access the App, but without success.
>
>
=============================================================================
> == R E C O M P I L E C O R E S C H E M A
>
=============================================================================
>
=============================================================================
> == A P P L I C A T I O N I N S T A L L A T I O N R E S U L T S
>
=============================================================================
>
>
> APP_ID WORKSPACE APPLICATION_NAME
> ---------- -------------------- ------------------------------
> 101 SERT APEX-SERT
> 102 SERT APEX-SERT Administration
>
=============================================================================
> == P O S T I N S T A L L A T I O N S T E P S
>
=============================================================================
>
> In order to be able to launch APEX-SERT, paste the following into the
System Message
> region in the INTERNAL workspace:
>
> <a href="javascript:var launchSERT=window.open('sert/launch/' +
$v('pInstance'));"><span class="a-Icon icon-run-page"></span>&nbsp;Launch
APEX-SERT</a>
>
> To access the APEX-SERT Admin application, enter the following URL while
> substituting HOST, PORT and DAD with those from your APEX environment:
>
> http(s)://HOST:PORT/DAD/f?p=SERT_ADMIN
>
> Please see the APEX-SERT Installation Guide for detailed
post-installation steps.
>
> connect as SV_SERT_LAUNCHER for SERT Launcher Web Service part 2
> ERROR:
> ORA-12514: Cannot connect to database. Service orcl is not registered
with the
> listener at host 127.0.0.1 port 1521.
(CONNECTION_ID=JWBoWPsFHS7gYwEAAH/HNQ==)
> Help: https://docs.oracle.com/error-help/db/ora-12514/
>
>
> ***@***.*** sert_240100]$
>
> I can also see a error for the PDF package in the logfile.
>
> 620/7 PL/SQL: Statement ignored
> 620/7 PLS-00905: object SV_SERT_240100.PL_FPDF is invalid
>
> Full logfile attached.
> SERT_install_2024-10-26_11-19-29.log
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.<
https://ci3.googleusercontent.com/meips/ADKq_NavHb9DJXtKTtAVyaDE5EiEq8Izvt1qqYkidBW2XhpajnQEEP4JzPMZTYW0gzuoN7wXD2pVIQknRutm27G03ZVfyCjGj0v96EWnNGf7ebCeGx_zwTo4xjEL839zO5wSdG-8kiv3psdBmimOsHEsgPXvHr9HNXlLNozISj4ffHTQ7uQieRpZ81RJSyHILlhmLMzEGC7MRCywvMFh_Mo_Spj_jItggvgqxzyua-Xa=s0-d-e1-ft#https://github.com/notifications/beacon/ABND76U6FOPB2HFPK5XWQJTZ5OBLPA5CNFSM6AAAAABQUX6XI6WGG33NNVSW45C7OR4XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHJX2SN2A.gif>Message
ID: ***@***.***>

**Comment by lschilde** [comment]
Same thing, before you run the install you need to change auto setup script parameters. Make sure that this works  
ORA-12514: Cannot connect to database. 

Service orcl is not registered else it will not be able to create a REST API that starts the app. 
What usually happens people do not configure line 69 correctly so this command fails

**connect SV_SERT_LAUNCHER/^schema_password@^db_conn_string** 

and hence API does not get created. 

With all said this will not fix the PDF packages, so you need to us a VM that is on 19c max at the moment. There it should work.

**Comment by iczcrash** [comment]
Thank you! I have installed APEX SERT on a 19c instance.
